
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Banner': typeof import("../components/Banner.vue")['default']
    'CreateDoctor': typeof import("../components/CreateDoctor.vue")['default']
    'CreateMedicine': typeof import("../components/CreateMedicine.vue")['default']
    'DeleteModal': typeof import("../components/DeleteModal.vue")['default']
    'DeletePatientModal': typeof import("../components/DeletePatientModal.vue")['default']
    'EditDoctorModal': typeof import("../components/EditDoctorModal.vue")['default']
    'EditPatientModal': typeof import("../components/EditPatientModal.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'FormLogin': typeof import("../components/FormLogin.vue")['default']
    'GraphOne': typeof import("../components/GraphOne.vue")['default']
    'GraphProgress': typeof import("../components/GraphProgress.vue")['default']
    'GraphTwo': typeof import("../components/GraphTwo.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'HeaderAbout': typeof import("../components/HeaderAbout.vue")['default']
    'Logout': typeof import("../components/Logout.vue")['default']
    'MedicineDelete': typeof import("../components/MedicineDelete.vue")['default']
    'MedicineDetail': typeof import("../components/MedicineDetail.vue")['default']
    'MedicineEdit': typeof import("../components/MedicineEdit.vue")['default']
    'NavBarAdministrator': typeof import("../components/NavBarAdministrator.vue")['default']
    'NavBarDoctor': typeof import("../components/NavBarDoctor.vue")['default']
    'TopPage': typeof import("../components/TopPage.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBanner': typeof import("../components/Banner.vue")['default']
    'LazyCreateDoctor': typeof import("../components/CreateDoctor.vue")['default']
    'LazyCreateMedicine': typeof import("../components/CreateMedicine.vue")['default']
    'LazyDeleteModal': typeof import("../components/DeleteModal.vue")['default']
    'LazyDeletePatientModal': typeof import("../components/DeletePatientModal.vue")['default']
    'LazyEditDoctorModal': typeof import("../components/EditDoctorModal.vue")['default']
    'LazyEditPatientModal': typeof import("../components/EditPatientModal.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyFormLogin': typeof import("../components/FormLogin.vue")['default']
    'LazyGraphOne': typeof import("../components/GraphOne.vue")['default']
    'LazyGraphProgress': typeof import("../components/GraphProgress.vue")['default']
    'LazyGraphTwo': typeof import("../components/GraphTwo.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyHeaderAbout': typeof import("../components/HeaderAbout.vue")['default']
    'LazyLogout': typeof import("../components/Logout.vue")['default']
    'LazyMedicineDelete': typeof import("../components/MedicineDelete.vue")['default']
    'LazyMedicineDetail': typeof import("../components/MedicineDetail.vue")['default']
    'LazyMedicineEdit': typeof import("../components/MedicineEdit.vue")['default']
    'LazyNavBarAdministrator': typeof import("../components/NavBarAdministrator.vue")['default']
    'LazyNavBarDoctor': typeof import("../components/NavBarDoctor.vue")['default']
    'LazyTopPage': typeof import("../components/TopPage.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Banner: typeof import("../components/Banner.vue")['default']
export const CreateDoctor: typeof import("../components/CreateDoctor.vue")['default']
export const CreateMedicine: typeof import("../components/CreateMedicine.vue")['default']
export const DeleteModal: typeof import("../components/DeleteModal.vue")['default']
export const DeletePatientModal: typeof import("../components/DeletePatientModal.vue")['default']
export const EditDoctorModal: typeof import("../components/EditDoctorModal.vue")['default']
export const EditPatientModal: typeof import("../components/EditPatientModal.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const FormLogin: typeof import("../components/FormLogin.vue")['default']
export const GraphOne: typeof import("../components/GraphOne.vue")['default']
export const GraphProgress: typeof import("../components/GraphProgress.vue")['default']
export const GraphTwo: typeof import("../components/GraphTwo.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const HeaderAbout: typeof import("../components/HeaderAbout.vue")['default']
export const Logout: typeof import("../components/Logout.vue")['default']
export const MedicineDelete: typeof import("../components/MedicineDelete.vue")['default']
export const MedicineDetail: typeof import("../components/MedicineDetail.vue")['default']
export const MedicineEdit: typeof import("../components/MedicineEdit.vue")['default']
export const NavBarAdministrator: typeof import("../components/NavBarAdministrator.vue")['default']
export const NavBarDoctor: typeof import("../components/NavBarDoctor.vue")['default']
export const TopPage: typeof import("../components/TopPage.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBanner: typeof import("../components/Banner.vue")['default']
export const LazyCreateDoctor: typeof import("../components/CreateDoctor.vue")['default']
export const LazyCreateMedicine: typeof import("../components/CreateMedicine.vue")['default']
export const LazyDeleteModal: typeof import("../components/DeleteModal.vue")['default']
export const LazyDeletePatientModal: typeof import("../components/DeletePatientModal.vue")['default']
export const LazyEditDoctorModal: typeof import("../components/EditDoctorModal.vue")['default']
export const LazyEditPatientModal: typeof import("../components/EditPatientModal.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyFormLogin: typeof import("../components/FormLogin.vue")['default']
export const LazyGraphOne: typeof import("../components/GraphOne.vue")['default']
export const LazyGraphProgress: typeof import("../components/GraphProgress.vue")['default']
export const LazyGraphTwo: typeof import("../components/GraphTwo.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyHeaderAbout: typeof import("../components/HeaderAbout.vue")['default']
export const LazyLogout: typeof import("../components/Logout.vue")['default']
export const LazyMedicineDelete: typeof import("../components/MedicineDelete.vue")['default']
export const LazyMedicineDetail: typeof import("../components/MedicineDetail.vue")['default']
export const LazyMedicineEdit: typeof import("../components/MedicineEdit.vue")['default']
export const LazyNavBarAdministrator: typeof import("../components/NavBarAdministrator.vue")['default']
export const LazyNavBarDoctor: typeof import("../components/NavBarDoctor.vue")['default']
export const LazyTopPage: typeof import("../components/TopPage.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
